"""
API Request and Response Models.

This file defines the structure/rules of the data
coming into and going out of our API.

Pydantic automatically validates the incoming data
and helps keep API responses consistent.
"""

from datetime import datetime, timezone

from pydantic import BaseModel, Field


# ================================================================
# CHAT REQUEST
# ================================================================

class ChatRequest(BaseModel):
    """
    Defines what the client/user must send to the chat API.

    Example request:

    {
        "message": "What is RAG?",
        "thread_id": "123"
    }
    """

    # User's actual message/question.
    #
    # min_length=1:
    # The message cannot be empty.
    #
    # max_length=1000:
    # The message cannot exceed 1000 characters.
    message: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="The user's message to the agent",
    )

    # Identifies the conversation.
    #
    # If the user doesn't provide a thread_id,
    # "default" will be used.
    thread_id: str = Field(
        default="default",
        description="The thread ID for the conversation",
    )


# ================================================================
# CHAT RESPONSE
# ================================================================

class ChatResponse(BaseModel):
    """
    Defines what our API sends back after processing a chat request.

    Example response:

    {
        "response": "RAG stands for Retrieval Augmented Generation.",
        "thread_id": "123",
        "model_used": "llama3.2",
        "cached": false,
        "processing_time_ms": 450.5,
        "timestamp": "2026-08-06T10:00:00+00:00",
        "security_notes": []
    }
    """

    # AI's final answer.
    response: str

    # Conversation/thread identifier.
    thread_id: str

    # Name of the AI model that generated the answer.
    model_used: str

    # True if the response came from cache.
    # False means the AI had to generate a new response.
    cached: bool = False

    # How long the request took to process.
    processing_time_ms: float

    # Time when the response was created.
    #
    # default_factory means this value is generated
    # automatically whenever a new response is created.
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    # NEW: Security notes generated while processing this request.
    #
    # Example values you might see in here:
    #
    #     "PII detected and masked: ['email']"
    #
    # This lets the CLIENT see (not just the server logs) that,
    # for example, an email address in the input was found and
    # replaced with [EMAIL] before being sent to the AI model.
    #
    # Defaults to an empty list when there's nothing to report.
    security_notes: list[str] = []


# ================================================================
# HEALTH RESPONSE
# ================================================================

class HealthResponse(BaseModel):
    """
    Defines the response from the health-check endpoint.

    Used to quickly check whether our API is running correctly.

    Example:

    {
        "status": "healthy",
        "environment": "production",
        "version": "1.0.0"
    }
    """

    # Current health status of the application.
    status: str = "healthy"

    # Current environment.
    # Example: development / staging / production.
    environment: str

    # Current API/application version.
    version: str = "1.0.0"

    # Additional health-check information.
    #
    # NOTE: renamed from "check" to "checks" (plural) because
    # main.py's /health endpoint builds a dict of component
    # checks and passes it in as:
    #
    #     return HealthResponse(
    #         status=...,
    #         environment=...,
    #         checks=checks,
    #     )
    #
    # The field name here must match that keyword exactly.
    checks: dict = {}


# ================================================================
# METRICS RESPONSE
# ================================================================

class MetricsResponse(BaseModel):
    """
    Defines the structure of application performance statistics.

    This can be used to monitor the API in production.
    """

    # Total number of requests received.
    total_requests: int

    # Total number of failed requests.
    total_errors: int

    # Percentage/rate of requests that failed.
    error_rate: str

    # Average time taken to process requests.
    average_latency_ms: float

    # Percentage of requests successfully served from cache.
    cache_hit_rate: str

    # Total tokens sent to the AI model.
    total_input_tokens: int

    # Total tokens generated by the AI model.
    total_output_tokens: int


# ================================================================
# ERROR RESPONSE
# ================================================================

class ErrorResponse(BaseModel):
    """
    Defines a standard format for API errors.

    Example:

    {
        "error": "Invalid request",
        "details": "Message cannot be empty",
        "request_id": "abc123"
    }
    """

    # Short description of the error.
    error: str

    # Optional detailed explanation.
    # None means details don't have to be provided.
    details: str | None = None

    # Optional ID used to track the specific request.
    request_id: str | None = None

"""
The important correction is: models.py doesn't generate the response. It defines the structure/rules for the data.

Think of it as a format/rule book 📋:

    ChatRequest → tells us what the user can send 📥
    ChatResponse → tells us what the user should receive 📤
    HealthResponse → tells us what a health check should look like ❤️
    MetricsResponse → tells us how monitoring data should look 📊
    ErrorResponse → tells us how errors should look ❌

So the easiest sentence is:
    models.py defines the rules and structure for the data coming into and going out of our API.
"""